version: "3.8"

services:
  app:
    build: .
    container_name: app_11
    restart: always
    ports:
      - "5050:5050"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:PassWord@db:5432/books11
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: lab11_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PassWord
      - POSTGRES_DB=books11

volumes:
  postgres_data:
