version: "3.8"

services:
  app:
    build: .
    container_name: app_11
    restart: always
    ports:
      - "5050:5050"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://admin:PassWord@db:3306/books11
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab11_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: books11
      MYSQL_USER: admin
      MYSQL_PASSWORD: PassWord
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
